### ISSUE TITLE
better packaging structure for slang CLI is needed 

### ISSUE THREAD

**Issue by meirwah** [openscore/score-language#4]
currently the batch file is under /appassembler/bin

need to change to maybe:
/slang/bin

**Comment by meirwah** [comment]
@orius123  don't froget to update the web-site too...

**Comment by meirwah** [comment]
@orius123 ? WDYT?

**Comment by orius123** [comment]
looks good, but we still need to zip it. another issue?

**Comment by meirwah** [comment]
we can merge this change... and keep commiting to this branch no?

**Comment by orius123** [comment]
yup. just don't close the issue. 
reviewd :white_check_mark:

**Comment by meshipeer** [comment]
add content library

**Comment by meirwah** [comment]
adding @hararzafrir

**Comment by meirwah** [comment]
@hararzafrir  please colse this when done..

**Comment by meirwah** [comment]
isn't this fixed already @oritstone @hararzafrir ?

**Comment by oritstone** [comment]
@orius123 is it done?

**Comment by orius123** [comment]
no. I need to handle it as part of the build task. do we want ot use this one or to open a new one?

**Comment by orius123** [comment]
ok.
I want to redefine this issue.
@openscore/owners please take two minutes to review :pray: 

### How to build:
- Use *nix OS (it might work on Windows :trollface: )
- Clone score-language repo
- Run:  
```bash
      cd score-language && 
      mvn clean install
```
- Download a stable version of slang-cli and run:
```bash
      slang run build/build_cli_flow.sl
```

## Tasks so the build will work: :wink: 
- [ ] Create a `build` directory in score-language repo
- [ ] Create a flow in `build` directory that:
  - [ ] Clone slang-content repo into `build`.
  - [ ] Runs verifier of the current maven build 
        (from `./score-lang-content-verifier/target/score-lang-content-verifier-<version>.jar`) 
         on the content repo, and checks that it succeeded.
  - [ ] Copy `score-lang-cli/target/slang` to `build` as `slang-cli`
  - [ ] **optional** pre-compile and repack `jython-standalone.jar` 
  - [ ] From build/slang-content repo copy `content` and `python-lib` directories into `build/slang-cli`
  - [ ] Run `pip install -t build/slang-cli/python-lib -r build/slang-cli/python-lib/requirements.txt`
  - [ ] Add execute permissions for `build/slang-cli/bin/slang`
  - [ ] Create build/slang-cli.zip from the slang-cli directory
  - [ ] Create build/slang-cli.tar.gz from the slang-cli directory

Anything I forgot?

**Comment by meirwah** [comment]
what is this needed : pre-compile and repack jython-standalone.jar ?
regarding docs, is see other projects use folder "docs" under root dir, like this : https://github.com/docker/docker/tree/master/docs

**Comment by orius123** [comment]
pre-compilation is for start up performance.

**Comment by orius123** [comment]
copied tasks to PR #151
